"""create domain and security schema

Revision ID: 0002_domain_security
Revises: 0001_foundation
Create Date: 2026-07-14 06:46:47.938323
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002_domain_security"
down_revision: str | Sequence[str] | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENUM_TYPE_NAMES = (
    "account_status",
    "account_type",
    "algorithm_family",
    "analyst_action_type",
    "audit_event_type",
    "contribution_category",
    "cyber_event_type",
    "data_sensitivity",
    "device_posture",
    "device_type",
    "event_severity",
    "incident_status",
    "migration_status",
    "quantum_priority",
    "recommended_action",
    "risk_level",
    "risk_segment",
    "scenario_key",
    "scenario_run_status",
    "session_status",
    "severity",
    "transaction_channel_code",
    "transaction_status",
    "user_role",
)


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_assets",
        sa.Column("crypto_asset_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "algorithm_family",
            postgresql.ENUM(
                "rsa",
                "ecc",
                "symmetric",
                "ml_kem",
                "ml_dsa",
                "hybrid",
                "other",
                name="algorithm_family",
            ),
            nullable=False,
        ),
        sa.Column(
            "data_sensitivity",
            postgresql.ENUM("low", "moderate", "high", "critical", name="data_sensitivity"),
            nullable=False,
        ),
        sa.Column("confidentiality_years", sa.Integer(), nullable=False),
        sa.Column("pqc_ready", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "migration_status",
            postgresql.ENUM(
                "not_assessed", "planned", "in_progress", "pqc_ready", name="migration_status"
            ),
            nullable=False,
        ),
        sa.Column("priority_score", sa.Integer(), nullable=False),
        sa.Column(
            "priority_level",
            postgresql.ENUM("low", "medium", "high", "urgent", name="quantum_priority"),
            nullable=False,
        ),
        sa.Column("assessment_reason", sa.Text(), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidentiality_years >= 0",
            name=op.f("ck_crypto_assets_confidentiality_years_nonnegative"),
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_crypto_assets_name_not_blank")),
        sa.CheckConstraint(
            "priority_score BETWEEN 0 AND 100", name=op.f("ck_crypto_assets_priority_score_range")
        ),
        sa.PrimaryKeyConstraint("crypto_asset_id", name=op.f("pk_crypto_assets")),
        sa.UniqueConstraint("name", name=op.f("uq_crypto_assets_name")),
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("home_city", sa.String(length=100), nullable=False),
        sa.Column("home_country", sa.String(length=2), nullable=False),
        sa.Column(
            "risk_segment",
            postgresql.ENUM("standard", "heightened", name="risk_segment"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0", name=op.f("ck_customers_display_name_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(home_country)) = 2", name=op.f("ck_customers_home_country_iso2")
        ),
        sa.PrimaryKeyConstraint("customer_id", name=op.f("pk_customers")),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", postgresql.ENUM("analyst", "admin", name="user_role"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "password_hash LIKE '$argon2id$%%'", name=op.f("ck_users_password_hash_argon2id")
        ),
        sa.CheckConstraint("email = lower(btrim(email))", name=op.f("ck_users_email_normalized")),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0", name=op.f("ck_users_display_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "account_type",
            postgresql.ENUM("savings", "current", name="account_type"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("active", "restricted", "closed", name="account_status"),
            nullable=False,
        ),
        sa.Column("typical_transaction_min_minor", sa.BigInteger(), nullable=False),
        sa.Column("typical_transaction_max_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "average_daily_transaction_count", sa.Numeric(precision=8, scale=2), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_accounts_currency_inr")),
        sa.CheckConstraint(
            "average_daily_transaction_count >= 0", name=op.f("ck_accounts_daily_count_nonnegative")
        ),
        sa.CheckConstraint(
            "typical_transaction_max_minor >= 0", name=op.f("ck_accounts_typical_max_nonnegative")
        ),
        sa.CheckConstraint(
            "typical_transaction_max_minor >= typical_transaction_min_minor",
            name=op.f("ck_accounts_typical_range_ordered"),
        ),
        sa.CheckConstraint(
            "typical_transaction_min_minor >= 0", name=op.f("ck_accounts_typical_min_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_accounts_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("account_id", "customer_id", name="uq_accounts_id_customer"),
    )
    op.create_table(
        "audit_events",
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "authentication_succeeded",
                "authentication_failed",
                "authorization_denied",
                "incident_created",
                "score_generated",
                "recommendation_generated",
                "analyst_action_recorded",
                "scenario_started",
                "scenario_completed",
                "scenario_failed",
                "scenario_reset",
                name="audit_event_type",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=320), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(entity_id)) > 0", name=op.f("ck_audit_events_entity_id_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(entity_type)) > 0", name=op.f("ck_audit_events_entity_type_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(request_id)) > 0", name=op.f("ck_audit_events_request_id_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.user_id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("audit_event_id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_entity_created_at",
        "audit_events",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_audit_events_request_id", "audit_events", ["request_id"], unique=False)
    op.execute(
        """
        CREATE FUNCTION prevent_audit_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'audit events are append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_append_only
        BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_events
        FOR EACH STATEMENT
        EXECUTE FUNCTION prevent_audit_event_mutation()
        """
    )
    op.create_table(
        "behavioural_baselines",
        sa.Column("baseline_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("sample_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sample_ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("typical_login_start_hour", sa.Integer(), nullable=False),
        sa.Column("typical_login_end_hour", sa.Integer(), nullable=False),
        sa.Column(
            "usual_cities",
            sa.ARRAY(sa.String(length=100)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "known_channels",
            sa.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("median_transaction_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("transaction_amount_mad_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "average_daily_transaction_count", sa.Numeric(precision=8, scale=2), nullable=False
        ),
        sa.Column("typical_beneficiary_age_days", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "average_daily_transaction_count >= 0",
            name=op.f("ck_behavioural_baselines_daily_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "median_transaction_amount_minor >= 0",
            name=op.f("ck_behavioural_baselines_median_amount_nonnegative"),
        ),
        sa.CheckConstraint(
            "sample_ended_at >= sample_started_at",
            name=op.f("ck_behavioural_baselines_sample_window_ordered"),
        ),
        sa.CheckConstraint(
            "transaction_amount_mad_minor >= 0",
            name=op.f("ck_behavioural_baselines_mad_nonnegative"),
        ),
        sa.CheckConstraint(
            "typical_beneficiary_age_days >= 0",
            name=op.f("ck_behavioural_baselines_beneficiary_age_nonnegative"),
        ),
        sa.CheckConstraint(
            "typical_login_end_hour BETWEEN 0 AND 23",
            name=op.f("ck_behavioural_baselines_login_end_hour_range"),
        ),
        sa.CheckConstraint(
            "typical_login_start_hour BETWEEN 0 AND 23",
            name=op.f("ck_behavioural_baselines_login_start_hour_range"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_behavioural_baselines_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("baseline_id", name=op.f("pk_behavioural_baselines")),
    )
    op.create_index(
        op.f("ix_behavioural_baselines_customer_id"),
        "behavioural_baselines",
        ["customer_id"],
        unique=False,
    )
    op.create_table(
        "beneficiaries",
        sa.Column("beneficiary_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("bank_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            postgresql.ENUM("low", "medium", "high", name="risk_level"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0", name=op.f("ck_beneficiaries_display_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_beneficiaries_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("beneficiary_id", name=op.f("pk_beneficiaries")),
        sa.UniqueConstraint("beneficiary_id", "customer_id", name="uq_beneficiaries_id_customer"),
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column(
            "device_type",
            postgresql.ENUM("desktop", "mobile", "tablet", name="device_type"),
            nullable=False,
        ),
        sa.Column("operating_system", sa.String(length=120), nullable=False),
        sa.Column("trusted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "posture",
            postgresql.ENUM("trusted", "unknown", "compromised", name="device_posture"),
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "last_seen_at >= first_seen_at", name=op.f("ck_devices_seen_window_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_devices_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("device_id", name=op.f("pk_devices")),
        sa.UniqueConstraint("customer_id", "fingerprint", name="uq_devices_customer_fingerprint"),
        sa.UniqueConstraint("device_id", "customer_id", name="uq_devices_id_customer"),
    )
    op.create_table(
        "transaction_channels",
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel_code",
            postgresql.ENUM("web_banking", "mobile_banking", name="transaction_channel_code"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("crypto_asset_id", sa.UUID(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0", name=op.f("ck_transaction_channels_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["crypto_asset_id"],
            ["crypto_assets.crypto_asset_id"],
            name=op.f("fk_transaction_channels_crypto_asset_id_crypto_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("channel_id", name=op.f("pk_transaction_channels")),
        sa.UniqueConstraint("channel_code", name=op.f("uq_transaction_channels_channel_code")),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("active", "ended", "revoked", name="session_status"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_sessions_time_window_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "customer_id"],
            ["accounts.account_id", "accounts.customer_id"],
            name="fk_sessions_account_customer",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["device_id", "customer_id"],
            ["devices.device_id", "devices.customer_id"],
            name="fk_sessions_device_customer",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_sessions")),
        sa.UniqueConstraint(
            "session_id",
            "customer_id",
            "account_id",
            "device_id",
            name="uq_sessions_device_identity",
        ),
        sa.UniqueConstraint("session_id", "customer_id", "account_id", name="uq_sessions_identity"),
    )
    op.create_table(
        "cyber_events",
        sa.Column("cyber_event_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "login_success",
                "login_failed",
                "mfa_success",
                "mfa_failed",
                "new_device",
                "risky_ip",
                "proxy_detected",
                "unusual_location",
                "impossible_travel",
                "unusual_login_time",
                "endpoint_alert",
                "session_token_anomaly",
                name="cyber_event_type",
            ),
            nullable=False,
        ),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "severity",
            postgresql.ENUM(
                "informational", "low", "medium", "high", "critical", name="event_severity"
            ),
            nullable=False,
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "customer_id", "account_id", "device_id"],
            [
                "sessions.session_id",
                "sessions.customer_id",
                "sessions.account_id",
                "sessions.device_id",
            ],
            name="fk_cyber_events_session_identity",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cyber_event_id", name=op.f("pk_cyber_events")),
    )
    op.create_index(
        "ix_cyber_events_session_event_time",
        "cyber_events",
        ["session_id", "event_time"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("beneficiary_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "permitted",
                "held",
                "released",
                "declined",
                "cancelled",
                name="transaction_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "destination_risk",
            postgresql.ENUM("low", "medium", "high", name="risk_level"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_transactions_currency_inr")),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_transactions_amount_nonnegative")),
        sa.ForeignKeyConstraint(
            ["beneficiary_id", "customer_id"],
            ["beneficiaries.beneficiary_id", "beneficiaries.customer_id"],
            name="fk_transactions_beneficiary_customer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["transaction_channels.channel_id"],
            name=op.f("fk_transactions_channel_id_transaction_channels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "customer_id", "account_id"],
            ["sessions.session_id", "sessions.customer_id", "sessions.account_id"],
            name="fk_transactions_session_identity",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("pk_transactions")),
        sa.UniqueConstraint(
            "transaction_id",
            "customer_id",
            "account_id",
            "session_id",
            name="uq_transactions_identity",
        ),
    )
    op.create_index(
        "ix_transactions_account_created_at",
        "transactions",
        ["account_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column(
            "scenario_key",
            postgresql.ENUM(
                "normal_activity", "legitimate_new_device", "account_takeover", name="scenario_key"
            ),
            nullable=True,
        ),
        sa.Column("cyber_score", sa.Integer(), nullable=False),
        sa.Column("transaction_score", sa.Integer(), nullable=False),
        sa.Column("correlation_bonus", sa.Integer(), nullable=False),
        sa.Column("fused_score", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            postgresql.ENUM("low", "guarded", "elevated", "high", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "recommended_action",
            postgresql.ENUM(
                "allow",
                "allow_and_monitor",
                "step_up_authentication",
                "hold_for_review",
                "hold_and_open_critical_incident",
                name="recommended_action",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "open",
                "in_review",
                "confirmed_fraud",
                "legitimate",
                "closed",
                name="incident_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "correlation_bonus BETWEEN 0 AND 18", name=op.f("ck_incidents_correlation_bonus_range")
        ),
        sa.CheckConstraint(
            "cyber_score BETWEEN 0 AND 100", name=op.f("ck_incidents_cyber_score_range")
        ),
        sa.CheckConstraint(
            "fused_score BETWEEN 0 AND 100", name=op.f("ck_incidents_fused_score_range")
        ),
        sa.CheckConstraint(
            "transaction_score BETWEEN 0 AND 100", name=op.f("ck_incidents_transaction_score_range")
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_incidents_update_time_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id", "customer_id", "account_id", "session_id"],
            [
                "transactions.transaction_id",
                "transactions.customer_id",
                "transactions.account_id",
                "transactions.session_id",
            ],
            name="fk_incidents_transaction_identity",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("incident_id", name=op.f("pk_incidents")),
    )
    op.create_index(
        "ix_incidents_customer_created_at", "incidents", ["customer_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_incidents_severity_created_at", "incidents", ["severity", "created_at"], unique=False
    )
    op.create_index(
        "ix_incidents_status_created_at", "incidents", ["status", "created_at"], unique=False
    )
    op.create_index("ix_incidents_transaction", "incidents", ["transaction_id"], unique=False)
    op.create_index(
        "uq_incidents_scenario_key",
        "incidents",
        ["scenario_key"],
        unique=True,
        postgresql_where=sa.text("scenario_key IS NOT NULL"),
    )
    op.create_table(
        "analyst_actions",
        sa.Column("analyst_action_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("analyst_id", sa.UUID(), nullable=False),
        sa.Column(
            "action_type",
            postgresql.ENUM(
                "add_note",
                "start_review",
                "mark_confirmed_fraud",
                "mark_legitimate",
                "simulate_hold",
                "simulate_release",
                "simulate_decline",
                "close_incident",
                name="analyst_action_type",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "previous_incident_status",
            postgresql.ENUM(
                "open",
                "in_review",
                "confirmed_fraud",
                "legitimate",
                "closed",
                name="incident_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "new_incident_status",
            postgresql.ENUM(
                "open",
                "in_review",
                "confirmed_fraud",
                "legitimate",
                "closed",
                name="incident_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "previous_transaction_status",
            postgresql.ENUM(
                "pending",
                "permitted",
                "held",
                "released",
                "declined",
                "cancelled",
                name="transaction_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "new_transaction_status",
            postgresql.ENUM(
                "pending",
                "permitted",
                "held",
                "released",
                "declined",
                "cancelled",
                name="transaction_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "previous_incident_status IS DISTINCT FROM new_incident_status "
            "OR previous_transaction_status IS DISTINCT FROM new_transaction_status "
            "OR action_type = 'add_note'",
            name=op.f("ck_analyst_actions_meaningful_action"),
        ),
        sa.CheckConstraint(
            "note IS NULL OR length(note) <= 2000", name=op.f("ck_analyst_actions_note_length")
        ),
        sa.ForeignKeyConstraint(
            ["analyst_id"],
            ["users.user_id"],
            name=op.f("fk_analyst_actions_analyst_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
            name=op.f("fk_analyst_actions_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("analyst_action_id", name=op.f("pk_analyst_actions")),
    )
    op.create_index(
        "ix_analyst_actions_incident_created_at",
        "analyst_actions",
        ["incident_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "risk_contributions",
        sa.Column("contribution_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "cyber_rule",
                "cyber_anomaly",
                "transaction_rule",
                "transaction_anomaly",
                "correlation",
                name="contribution_category",
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("source_event_id", sa.UUID(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "category <> 'correlation' OR points <= 18",
            name=op.f("ck_risk_contributions_correlation_points_cap"),
        ),
        sa.CheckConstraint(
            "category NOT IN ('cyber_anomaly', 'transaction_anomaly') OR points <= 10",
            name=op.f("ck_risk_contributions_anomaly_points_cap"),
        ),
        sa.CheckConstraint(
            "display_order >= 0", name=op.f("ck_risk_contributions_display_order_nonnegative")
        ),
        sa.CheckConstraint(
            "points BETWEEN 0 AND 100", name=op.f("ck_risk_contributions_points_range")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
            name=op.f("fk_risk_contributions_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["cyber_events.cyber_event_id"],
            name=op.f("fk_risk_contributions_source_event_id_cyber_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("contribution_id", name=op.f("pk_risk_contributions")),
        sa.UniqueConstraint("incident_id", "code", name="uq_contributions_incident_code"),
    )
    op.create_table(
        "scenario_runs",
        sa.Column("scenario_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "scenario_key",
            postgresql.ENUM(
                "normal_activity", "legitimate_new_device", "account_takeover", name="scenario_key"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "not_run", "running", "completed", "failed", name="scenario_run_status"
            ),
            nullable=False,
        ),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("simulation_epoch", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("result_incident_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_scenario_runs_time_window_ordered"),
        ),
        sa.CheckConstraint("seed >= 0", name=op.f("ck_scenario_runs_seed_nonnegative")),
        sa.ForeignKeyConstraint(
            ["result_incident_id"],
            ["incidents.incident_id"],
            name=op.f("fk_scenario_runs_result_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("scenario_run_id", name=op.f("pk_scenario_runs")),
        sa.UniqueConstraint("run_fingerprint", name=op.f("uq_scenario_runs_run_fingerprint")),
        sa.UniqueConstraint("scenario_key", name=op.f("uq_scenario_runs_scenario_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario_runs")
    op.drop_table("risk_contributions")
    op.drop_index("ix_analyst_actions_incident_created_at", table_name="analyst_actions")
    op.drop_table("analyst_actions")
    op.drop_index(
        "uq_incidents_scenario_key",
        table_name="incidents",
        postgresql_where=sa.text("scenario_key IS NOT NULL"),
    )
    op.drop_index("ix_incidents_transaction", table_name="incidents")
    op.drop_index("ix_incidents_status_created_at", table_name="incidents")
    op.drop_index("ix_incidents_severity_created_at", table_name="incidents")
    op.drop_index("ix_incidents_customer_created_at", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_transactions_account_created_at", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_cyber_events_session_event_time", table_name="cyber_events")
    op.drop_table("cyber_events")
    op.drop_table("sessions")
    op.drop_table("transaction_channels")
    op.drop_table("devices")
    op.drop_table("beneficiaries")
    op.drop_index(op.f("ix_behavioural_baselines_customer_id"), table_name="behavioural_baselines")
    op.drop_table("behavioural_baselines")
    op.drop_index("ix_audit_events_request_id", table_name="audit_events")
    op.drop_index("ix_audit_events_entity_created_at", table_name="audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
    op.drop_table("audit_events")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("customers")
    op.drop_table("crypto_assets")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_event_mutation()")
    for enum_type_name in ENUM_TYPE_NAMES:
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_type_name}"'))
    # ### end Alembic commands ###
